apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  # alerting:
  #   alertmanagers:
  #     - namespace: monitoring
  #       name: alertmanager-operated
  #       port: web
  # ruleSelector:
  #   matchLabels:
  #     prometheus: main
  # ruleNamespaceSelector:
  #   matchLabels:
  #     monitoring: prometheus
  version: v2.42.0
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  #   matchLabels:
  #     prometheus: main
  podMonitorNamespaceSelector: {}
  #   matchLabels:
  #     monitoring: prometheus
  # serviceMonitorSelector:
  #   matchLabels:
  #     prometheus: main
  # serviceMonitorNamespaceSelector: {}
  #   matchLabels:
  #     monitoring: prometheus
  # probeSelector:
  #   matchLabels:
  #     prometheus: main
  # probeNamespaceSelector:
  #   matchLabels:
  #     monitoring: prometheus
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  resources:
    requests:
      cpu: 500m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 400Mi
 # replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 7d
  scrapeInterval: 15s
  enableAdminAPI: true
  # securityContext:
  #   fsGroup: 0
  #   runAsNonRoot: false
  #   runAsUser: 0
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           storage: 20Gi
  remoteWrite:
     - url: "http://ec2-65-0-87-53.ap-south-1.compute.amazonaws.com:30900/api/v1/read"
       name: prometheus-k8s-test
       remoteTimeout: 1m
       queueConfig: 
         capacity: 1000000
         maxShards: 1000
         maxSamplesPerSend: 1000
         batchSendDeadline: 5s
         minBackoff: 30ms
         maxBackoff: 100ms